---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recall-app-secrets
  namespace: recall-app
spec:
  encryptedData:
    ORIGIN_VERIFY_SECRET: AgA4SJ7V49F5u33qu2Xip/TBNKvj7zxSJ61oChsE5EEL+qrWShYg0nn9djm2W/VM6m90bwwO0wlwJfKjkHq+9+F9csaC+mf7vbvX4mE1MEDbUY5Rr3DC3gR5QykRLfLsqMZZGZc9inRx27qScpp397PcPLnITPgxgm+dVmG16+4DdKBlZ+X/GGWsxNLlaOtbx53fZsAePqVK/Jk6eHM+otbcJs6u4zKuLVsY/iq1mGIdDHRILniy5IjeUmWfkYBAJJ2Ct/8+2/aWXOAovtHYpij0VxATZLSz89pWQThn1rUhb8Igtb84a1Bd/yHAaDYrUuTvT/akxH9lhoVC5dUI619Nu36vfBFjuKdsH3Zl+rgCSWRP3R3v+A4ZVE1pcovCrd9475ToOpNY4u9Q7bH6NLto5uIau3+xCyWOdOrsHq++OsYdxYVgRwz9ijIBMRxm8eQmW+t60LAVpWtL6YAFH7bp6k4sByxgPhXYuYCeAzhk8M5DGypiIJ90ZdDWXMjrp5BRF+ps4xi1f7cEmJNLh6y+iXEoZpF79rp9cCUcEFXt4Eta2q62yk+VRXpNyi8SGL4f0fSquAmZQsoKcChtl4h3fWa7Tj0ig1x7CIjsymTh+FmHAdlRxP92tfgxLZzpRWgfjNA92kxr3Vz7LXVdFG1RnXPVn6mSWSzFb3m7cmLiLu+pJroTQAWEKeIYjjIzQTHyohnnyQ7MT73fA6aBm9h5zQrn7xxbUj7S8FZxAcB9Z4+90DRbVjz9SeFURXjJUXW+x6hGFHZ4GbpijjUIc9EH
  template:
    metadata:
      name: recall-app-secrets
      namespace: recall-app
    type: Opaque
